@startuml
autonumber
title Secuencia: GetMovements (reactivo)
' Descripción: Obtiene movimientos consultando TransactionService tras verificación de acceso.

participant Customer
participant AccountService
participant CustomerService
participant TransactionService

Customer ->> AccountService : getMovements(accountId, page) : Flux<MovementDto>
AccountService ->> CustomerService : verifyAccess(customerId, accountId) : Mono<AccessResult>
CustomerService -->> AccountService : AccessResult{allowed:true}

alt acceso permitido
  AccountService ->> TransactionService : listMovements(accountId, page) : Flux<Movement>
  TransactionService -->> AccountService : Flux<Movement>
  Account -->> Customer : Flux<MovementDto>
else denegado
  AccountService -->> Customer : error(AccessDenied)
end
@enduml
